demo/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$','demo.views.ingresar', name="ingresar"),
    url(r'^privado/', 'demo.views.privado', name="privado"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cerrar/', 'demo.views.cerrar', name="cerrar"),
    url(r'^logout/$','django.contrib.auth.views.logout_then_login',name='logout'),
    url(r'^usuario/', include('sgpa.urls', namespace='usuario'))

)

sgpa/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:

urlpatterns = patterns('',

     url(r'^asignar_rol_de_proyecto/(?P<id_usuario>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.asignar_rol_de_proyecto', name="asignar_rol_de_proyecto"),
     url(r'^detallesprint/(?P<id_sprint>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.detalle_sprint', name="detallesprint"),
     url(r'^equipo_rol/(?P<id_proyecto>\d+)/(?P<id_equipo>\d+)/$', 'sgpa.views.equipo_rol', name="equipo_rol"),
     url(r'^descargar/(?P<archivo_id>\d+)/$', 'sgpa.views.descargar', name="descargar"),
     url(r'^descarga_view/(?P<id_hu>\d+)/$', 'sgpa.views.descarga_view', name="descarga_view"),
     url(r'^flujo_proyecto/(?P<id_proyecto>\d+)/$', 'sgpa.views.flujo_proyecto', name="flujo_proyecto"),
     url(r'^agregar_flujo/(?P<id_proyecto>\d+)/$', 'sgpa.views.agregar_flujo', name="agregar_flujo"),
     url(r'^agregar_trabajo/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.agregar_trabajo',name="agregar_trabajo"),
     url(r'^avanzar/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.avanzar', name="avanzar"),
     url(r'^retroceder/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.retroceder', name="retroceder"),
     url(r'^ver_trabajo/(?P<id_hu>\d+)/(?P<orden>\d+)/$', 'sgpa.views.ver_trabajo_view',name="ver_trabajo"),
     url(r'^finalizar/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.finalizar', name="finalizar"),
     url(r'^finalizar_proyecto/(?P<codigo>\d+)/$', 'sgpa.views.finalizar_proyecto', name="finalizar_proyecto"),

     url(r'^seleccionar_flujo/(?P<id_hu>\d+)/(?P<id_sprint>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.seleccionar_flujo', name="seleccionar_flujo"),
     url(r'^respon/(?P<id_hu>\d+)/(?P<codigo>\d+)/(?P<id_sprint>\d+)/(?P<hus>[^/]+)/$', 'sgpa.views.responsable', name="respon"),
     url(r'^flujo/(?P<id_hu>\d+)/(?P<codigo>\d+)/(?P<id_sprint>\d+)/(?P<hus>[^/]+)/$', 'sgpa.views.flujo', name="flujo"),
     url(r'^editar_responsable/(?P<id_hu>\d+)/(?P<id_proyecto>\d+)/(?P<id_sprint>\d+)/$', 'sgpa.views.editar_responsable', name="editar_responsable"),
     url(r'^editar_flujo/(?P<id_hu>\d+)/(?P<id_proyecto>\d+)/(?P<id_sprint>\d+)/$', 'sgpa.views.editar_flujo', name="editar_flujo"),
     url(r'^cambiar_flujo/(?P<id_hu>\d+)/(?P<id_proyecto>\d+)/$', 'sgpa.views.cambiar_flujo', name="cambiar_flujo"),

     url(r'^crearhu/(?P<codigo>\d+)/$', 'sgpa.views.nuevo_hu', name="crearhu"),
     url(r'^gestionarsprint/(?P<codigo>\d+)/$', 'sgpa.views.gestionar_sprint', name="gestionarsprint"),
     url(r'^activarsprint/(?P<codigo>\d+)/$', 'sgpa.views.activar_sprint', name="activarsprint"),
     url(r'^sprintbacklog/(?P<id_sprint>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.sprint_backlog', name="sprintbacklog"),
     url(r'^asignarresponsable/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.asignar_responsable', name="asignarresponsable"),

     url(r'^asignarflujosprint/(?P<id_sprint>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.asignar_flujo_sprint', name="asignarflujosprint"),
     url(r'^iniciar/(?P<id_sprint>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.iniciar', name="iniciar"),

     url(r'^asignarhusprint/(?P<id_proyecto>\d+)/(?P<id_sprint>\d+)/$', 'sgpa.views.asignar_hu_a_sprint', name="asignarhusprint"),
     url(r'^asignarresponsable/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.asignar_responsable', name="asignarresponsable"),
     url(r'^historialhu/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.historial_hu', name="historialhu"),
     url(r'^cambiar_estado_de_hu/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.cambiar_estado_de_hu', name="cambiar_estado_de_hu"),

     url(r'^adminhu/(?P<codigo>\d+)/$', 'sgpa.views.hu_admin', name="adminhu"),
     url(r'^detalle_hu/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.detalle_hu_view', name = "detalle_hu"),
     url(r'^modificar_hu/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.modificar_hu_view', name = "modificar_hu"),
     url(r'^eliminarhu/(?P<id_hu>\d+)/(?P<codigo>\d+)/$', 'sgpa.views.eliminar_hu', name = "eliminarhu"),


     url(r'^administrar', 'sgpa.views.usuario_admin', name="administrar"),
     url(r'^equipo_trabajo/(?P<id_proyecto>\d+)/$', 'sgpa.views.equipo_trabajo', name="equipo_trabajo"),
     url(r'^lista_eliminar_miembro/(?P<id_proyecto>\d+)/$', 'sgpa.views.lista_eliminar_miembro', name="lista_eliminar_miembro"),
     url(r'^detalle_equipo/(?P<id_proyecto>\d+)/$', 'sgpa.views.detalle_equipo', name="detalle_equipo"),
     url(r'^eliminar_miembro/(?P<proyect_id>\d+)/(?P<usu_id>\d+)/$', 'sgpa.views.eliminar_miembro', name="eliminar_miembro"),
     url(r'^asignar_cliente_a_usuario/(?P<codigo>\d+)/$', 'sgpa.views.asignar_cliente_a_usuario', name="asignar_cliente_a_usuario"),
     url(r'^asignar_rol_de_sistema/(?P<codigo>\d+)/$', 'sgpa.views.asignar_rol_de_sistema_a_usuario', name="asignar_rol_de_sistema"),
     url(r'^cambiar_estado_de_usuario/(?P<codigo>\d+)/$', 'sgpa.views.cambiar_estado_de_usuario', name="cambiar_estado_de_usuario"),
     url(r'^cambiar_estado_de_proyecto/(?P<codigo>\d+)/$', 'sgpa.views.cambiar_estado_de_proyecto', name="cambiar_estado_de_proyecto"),
     url(r'^cambiar_estado_de_cliente/(?P<codigo>\d+)/$', 'sgpa.views.cambiar_estado_de_cliente', name="cambiar_estado_de_cliente"),

     url(r'^reasignar_lider/(?P<codigo>\d+)/$', 'sgpa.views.reasignar_lider_de_proyecto', name="reasignar_lider"),

     url(r'^crearcliente', 'sgpa.views.nuevo_cliente', name="crearcliente"),
     url(r'^adminproyecto', 'sgpa.views.proyecto_admin', name="adminproyecto"),
     url(r'^crearproyecto', 'sgpa.views.registrarProyecto', name="crearproyecto"),
     url(r'^adminrolsistema', 'sgpa.views.administrar_rol_de_sistema', name="adminrolsistema"),
     url(r'^adminrolproyecto', 'sgpa.views.administrar_rol_de_proyecto', name="adminrolproyecto"),
     url(r'^crearrolproyecto', 'sgpa.views.nuevo_rol_de_proyecto', name="crearrolproyecto"),
     url(r'^crearrolsistema', 'sgpa.views.nuevo_rol_de_sistema', name="crearrolsistema"),
     url(r'^modificar_proyecto/(?P<id_proyecto>\d+)/$', 'sgpa.views.modificar_proyecto_view', name = "modificar_proyecto"),
     url(r'^detalle_proyecto_desarrollo/(?P<id_proyecto>\d+)/$', 'sgpa.views.detalle_proyecto_view_desarrollo', name = "detalle_proyecto_desarrollo"),
     url(r'^detalle_proyecto/(?P<id_proyecto>\d+)/$', 'sgpa.views.detalle_proyecto_view', name = "detalle_proyecto"),
     url(r'^detalle_cliente/(?P<codigo>\d+)/$', 'sgpa.views.detalle_cliente', name = "detalle_cliente"),
     url(r'^detalle_rol_proyecto/(?P<codigo>\d+)/$', 'sgpa.views.detalle_rol_proyecto', name = "detalle_rol_proyecto"),
     url(r'^detalle_rol_sistema/(?P<codigo>\d+)/$', 'sgpa.views.detalle_rol_sistema', name = "detalle_rol_sistema"),
     url(r'^detalle_usuario/(?P<id_usuario>\d+)/$', 'sgpa.views.detalle_usuario_view', name = "detalle_usuario"),
     url(r'^modificar_rol_sistema/(?P<codigo>\d+)/$', 'sgpa.views.modificar_rol_sistema', name="modificar_rol_sistema"),
     url(r'^modificar_rol_proyecto/(?P<codigo>\d+)/$', 'sgpa.views.modificar_rol_proyecto', name="modificar_rol_proyecto"),

     url(r'^modificar_usuario/(?P<id_usuario>\d+)/$', 'sgpa.views.modificar_usuario_view', name = "modificar_usuario"),
     url(r'^eliminar_usuario/(?P<codigo>\d+)/$', 'sgpa.views.eliminar_usuario', name = "eliminar_usuario"),
     url(r'^eliminar_rol_proyecto/(?P<codigo>\d+)/$', 'sgpa.views.eliminar_rol_proyecto', name = "eliminar_rol_proyecto"),
     url(r'^eliminar_rol_sistema/(?P<codigo>\d+)/$', 'sgpa.views.eliminar_rol_sistema', name = "eliminar_rol_sistema"),

     url(r'^eliminar_proyecto/(?P<codigo>\d+)/$', 'sgpa.views.eliminar_proyecto', name = "eliminar_proyecto"),
     url(r'^modificar_password/', 'django.contrib.auth.views.password_change', name='modificar_password'),
     url(r'^search', 'sgpa.views.search', name="search"),
     url(r'^admincliente', 'sgpa.views.cliente_admin', name="admincliente"),
     url(r'^administracion', 'sgpa.views.administracion', name="administracion"),

     url(r'^modificar_cliente/(?P<id_cliente>\d+)/$', 'sgpa.views.modificar_cliente_view', name = "modificar_cliente"),
     url(r'^eliminar_cliente/(?P<codigo>\d+)/$', 'sgpa.views.eliminar_cliente', name = "eliminar_cliente"),

     url(r'^gestionar_flujo', 'sgpa.views.gestionar_flujo', name="gestionar_flujo"),
     url(r'^crearflujo', 'sgpa.views.nuevo_flujo', name="crearflujo"),
     url(r'^detalle_flujo/(?P<id_flujo>\d+)/$', 'sgpa.views.detalle_flujo_view', name = "detalle_flujo"),
     url(r'^modificar_flujo/(?P<id_flujo>\d+)/$', 'sgpa.views.modificar_flujo', name = "modificar_flujo"),
     url(r'^eliminar_flujo/(?P<codigo>\d+)/$', 'sgpa.views.eliminar_flujo', name = "eliminar_flujo"),
     url(r'^ingresar_Proyecto/(?P<codigo>\d+)/$', 'sgpa.views.ingresar_Proyecto', name = "ingresar_Proyecto"),
     url(r'^datos_Proyecto/(?P<id_proyecto>\d+)/$', 'sgpa.views.datos_Proyecto', name = "datos_Proyecto"),
     url(r'^agregar_actividad/(?P<flujo_id>\d+)/$', 'sgpa.views.agregar_actividad', name = "agregar_actividad"),
     url(r'^crear_usuario', 'sgpa.views.nuevo_usuario', name="crear_usuario")
)

demo/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from sgpa.util import obtenerPermisos, obtenerPermisosSistema


def ingresar(request):

    '''
    controla si el usuario se encuentra registrado, permite iniciar sesion
    \n@param request:
    \n@return retorna a la siguiente intefaz
    C{import} Importa variables.
    C{variables} todas las variables.
    :param request:
    :return:
    '''

    if not request.user.is_anonymous():
        return HttpResponseRedirect('/privado')
    if request.method == 'POST':
        formulario = AuthenticationForm(request.POST)
        if formulario.is_valid:
            nombreDeUsuario = request.POST['username']
            password = request.POST['password']
            usuario = authenticate(username=nombreDeUsuario, password=password)
            if usuario is not None:
                if usuario.is_active:
                    login(request, usuario)
                    return HttpResponseRedirect('/privado')
                else:
                    return render_to_response('noactivo.html', context_instance=RequestContext(request))
            else:
                return render_to_response('nousuario.html', context_instance=RequestContext(request))
    else:
        formulario = AuthenticationForm()
    return render_to_response('ingresar.html',{'formulario':formulario,}, context_instance=RequestContext(request))

@login_required()
def privado(request):
    """recibe un @param request
        Permite acceder a los servicos del sistema.
    \n@return a la interfaz principal"""
    usuario = request.user
    permisos = obtenerPermisos(request)

    return render_to_response('privado.html', {'usuario':usuario,'permisos':permisos},context_instance=RequestContext(request))

@login_required()
def cerrar(request):
    """funcion que cierra la sesion de un usuario registrado y logeado en el sistema, \nrecibe como @param un request
    y \n@return a la interfaz de inicio sesion"""
    logout(request)
    return HttpResponseRedirect('/')

demo/templates/administrar_rol_de_sistema.html
{% extends 'administracion.html' %}
{% block contenido %}
<div class="histo-detalle">
    <a href="/"><font color="#3D9A13"> home </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/adminrolsistema"><font color="#3D9A13"> Rol de Sistema </font></a>
</div>
<nav class="detalle">

        <h1>Administrar Rol de Sistema</h1>
    {%if roles %}
        <div class="content">
            <table class="max">
                <thead>
                <tr>
                    <th class="thead">Rol</th>
                    <th width="75px" class="tnuevo"><span class="pushbutton"><a href="{% url 'usuario:crearrolsistema' %}" class="current"> <img src="/static/img/nuevo2.png" width="25" height="25" /></a></span></th>
                </tr>
                </thead>
                {% for rol in roles %}
                    <tbody>
                    <tr>
                        <td>{{rol.nombre}}</td>
                        <td><ul id="nav">
                            <li><span class="pushbutton"><a href="#" class="current" ><span><img src="/static/img/botonmenu2.png" alt="detalle"title="ver detalle" width="25" height="25" ></span></a></span>
                                <div class="subs">

                                    <div class="col">
                                        <ul>
                                            <li><a href='/usuario/detalle_rol_sistema/{{rol.id}}'><img src="/static/img/detalle.png" width="25" height="25"/> Ver</a></li>
                                            {% if not rol.nombre == "administrador"%}
                                            <li><a onclick="return pregunta_rol()" href='/usuario/eliminar_rol_sistema/{{rol.id}}'><img src="/static/img/eliminar3.png" width="25" height="25"/> Eliminar</a></li>
                                            {%endif%}
                                        </ul>
                                    </div>
                                    <div class="col">
                                        <ul>
                                            {%if not rol.nombre == "administrador"%}
                                            <li><a href='/usuario/modificar_rol_sistema/{{rol.id}}'><img src="/static/img/editar2.png" width="25" height="25" /> Modificar</a></li>
                                            {%endif%}
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        </ul></td>
                    </tr>
                    </tbody>
                {%endfor%}
            </table>
        </div>
    {%else%}
        <font color="red">No hay roles registrados, presiona</font> <a href="{% url 'usuario:crearrolsistema' %}" class="current">Aqui </a><font color="red">para crear uno nuevo</font>
    {%endif%}
     <a href="{% url 'usuario:administracion' %}javascript:window.history.back();" class="button-highlight button">Atras</a>
</nav>

{%endblock%}

demo/templates/asignar_responsable_flujo.html
{% extends 'Base.html' %}
{% block titulo %}Asignar Flujo{% endblock %}
{% block encabezado %}
<h1> Asigne las Historias de Usuario</h1>
{% endblock %}
{% block privado%}{% endblock%}
{% block contenido %}
<div class="histo-detalle">
    <a href="/"><font color="#3D9A13"> home </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/ingresar_Proyecto/{{codigo}}"><font color="#3D9A13"> Proyectos </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/datos_Proyecto/{{proyecto.id}}"><font color="#3D9A13"> {{proyecto}} </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="#"><font color="#3D9A13"> Crear Sprint </font></a>
</div>
<div id="wrapper">

	<ul class="menu">
		{%if 'asignar equipo' in permisos %}:
		    <li class="item1"><a href="#">Equipo</a>
			   <ul>
				<li class="subitem1"><a href="/usuario/equipo_trabajo/{{proyecto.id}}">Agregar Miembro</a></li>
                <li class="subitem1"><a href="/usuario/lista_eliminar_miembro/{{proyecto.id}}">Eliminar Miembro</a></li>
				<li class="subitem2"><a href="/usuario/detalle_equipo/{{proyecto.id}}">Ver Equipo </a></li>
			</ul>
		   </li>
        {%endif%}
		<li class="item2"><a href="#">Historia de Usuario</a>
			<ul>
				<li class="subitem1"><a href='/usuario/adminhu/{{proyecto.id}}'>Administrar HU </a></li>
			</ul>
		</li>
		<li class="item3"><a href="#">Sprint </a>
			<ul>
				<li class="subitem1"><a href="/usuario/activarsprint/{{proyecto.id}}">Crear Sprint</a></li>
				<li class="subitem2"><a href="/usuario/gestionarsprint/{{proyecto.id}}">Ver Sprint </a></li>
			</ul>
		</li>
        <li class="item3"><a href="#">Flujo</a>
			<ul>
				<li class="subitem1"><a href="#">Agregar Flujo</a></li>
				<li class="subitem2"><a href="#">Ver Flujo </a></li>
			</ul>
		</li>
	</ul>

</div>
<!--initiate accordion-->
<script type="text/javascript">
	$(function() {

	    var menu_ul = $('.menu > li > ul'),
	           menu_a  = $('.menu > li > a');

	    menu_ul.hide();

	    menu_a.click(function(e) {
	        e.preventDefault();
	        if(!$(this).hasClass('active')) {
	            menu_a.removeClass('active');
	            menu_ul.filter(':visible').slideUp('normal');
	            $(this).addClass('active').next().stop(true,true).slideDown('normal');
	        } else {
	            $(this).removeClass('active');
	            $(this).next().stop(true,true).slideUp('normal');
	        }
	    });

	});
</script>
<nav class="detalle">
    <h1>{{proyecto}}</h1>
    <hr/>
    <h1>Asignar Responsable y Flujo</h1>
    <br><br>
    {%for h in hus%}
        <div class="responsable-flujo" >
             <div class="cabezera-rf">
                 <h1>{{h}}</h1>
             </div>
            <div class="responsable">
                <h1>Seleccione un responsable para la HU</h1>
                <div class="responsable-img" >
                    {%if not h.responsable %}
                    <a href='/usuario/respon/{{h.id}}/{{proyecto.id}}/{{sprint.id}}/{{hus_id}}'><img src="/static/img/eliminar.png" width="25" height="25" /></a>
                    {%else%}
                    <a href='/usuario/respon/{{h.id}}/{{proyecto.id}}/{{sprint.id}}/{{hus_id}}'><img src="/static/img/check.png" width="25" height="25" /></a>
                    {%endif%}
                </div>
            </div>
            <div class="flujo">
                <h1>Seleccione un Flujo para la HU</h1>

                <div class="flujo-img" >
                    {%if not h.flujo %}
                    <a href='/usuario/flujo/{{h.id}}/{{proyecto.id}}/{{sprint.id}}/{{hus_id}}'><img src="/static/img/eliminar.png" width="25" height="25" /></a>
                    {%else%}
                    <a href='/usuario/flujo/{{h.id}}/{{proyecto.id}}/{{sprint.id}}/{{hus_id}}'><img src="/static/img/check.png" width="25" height="25" /></a>
                    {%endif%}
                </div>
            </div>
        </div>
    {%endfor%}
</nav>

{%endblock%}

demo/templates/cambiar_estado_de_cliente.html
{% extends 'administracion.html' %}
{% if user.is_active %}
 {% block titulo %}Cambio de estado de Cliente{% endblock %}
{% block privado%}{% endblock%}
{% block contenido %}
<div class="histo-detalle">
    <a href="/"><font color="#3D9A13"> home </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/admincliente"><font color="#3D9A13"> Administrar Cliente </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/cambiar_estado_de_cliente/{{cliente.id}}"><font color="#3D9A13"> Cambiar Estado / {{cliente}} </font></a>
</div>
<nav class="detalle">
    <h1>Cambiar estado del cliente {{cliente}}</h1>>
    <form method='post' action=''>{% csrf_token %}
                <table class="max">

                    {{formulario}}

                </table>
                <button class="button button-action" type="submit" name="Guardar" />Guardar</button>
                    <a class="button button-caution" href="{% url 'usuario:admincliente' %}">Cancelar</a>
    </form>
</nav>


{% endblock %}
{% endif%}

demo/templates/datonovalido.html
{% extends 'Base.html' %}
{% block encabezado %}
<h1>Error</h1>
{% endblock %}
{% block contenido %}
<h2><p><center>Error</center></h2></p>
<p><center> La fecha de inicio del proyecto debe ser menor que la fecha de finalizacion.</center> </p>
<li><center><a href="{% url 'usuario:crearproyecto' %}"><i class="icon-chevron-right"></i>Volver</a></center></li>
{% endblock %}

demo/templates/modificar_rol.html
{% extends 'Base.html' %}
{% if user.is_active %}
 {% block titulo %}Modificar Rol{% endblock %}
{% block encabezado %}
<h1>Usted esta modificando el rol {{rol.nombre}} </h1>
{% endblock %}
{% block privado%}{% endblock%}
{% block contenido %}
<form method='post' action=''>{% csrf_token %}
    <table>{{formulario}}</table>

    <button type="submit" name="Guardar" />Guardar</button>

    <a href="{% url 'usuario:adminrol' %}"><button type="button">Cancelar</button>

</form>
{% endblock %}
{% endif%}

demo/templates/nuevoRol.html
{% extends 'Base.html' %}
{% if user.is_active %}
 {% block titulo %}Nuevo Proyecto{% endblock %}
{% block encabezado %}
<h1>Registre un nuevo Rol </h1>
{% endblock %}
{% block privado%}{% endblock%}
{% block contenido %}
<form method='post' action="{% url 'usuario:crearrol' %}">{% csrf_token %}

	<table class="max">{{form}}</table>

    <button type="submit" name="Guardar" />Guardar<r</form>/button>

    <a href="{% url 'usuario:adminrol' %}"><button type="button">Cancelar</button>

</form>
{% endblock %}
{% endif %}

demo/templates/nuevoRolSistema.html
{% extends 'administracion.html' %}
{% if user.is_active %}
 {% block titulo %}Nuevo Rol de Sistema{% endblock %}
{% block privado%}{% endblock%}
{% block contenido %}
<div class="histo-detalle">
    <a href="/"><font color="#3D9A13"> home </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/adminrolsistema"><font color="#3D9A13"> Rol de Sistema </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/crearrolsistema"><font color="#3D9A13"> Nuevo </font></a>
</div>
<nav class="detalle">
    <h1>NUEVO ROL DE SISTEMA</h1>
    <table>
        <form action="{% url 'usuario:crearrolsistema' %}" method="post">
        {% csrf_token%}
        <table class="max">{{form}}</table>

        <button class="button button-action" type="submit" name="Guardar" />Guardar</button>
        <a class="button button-caution" href="{% url 'usuario:adminrolsistema' %}">Cancelar</a>
</form>

    </table>

{% endblock %}
{% endif%}

demo/templates/nuevo_proyecto.html
{% extends 'administracion.html' %}
{% if user.is_active %}
 {% block titulo %}Nuevo Proyecto{% endblock %}
{% block privado%}{% endblock%}
{% block contenido %}
<div class="histo-detalle" xmlns="http://www.w3.org/1999/html">
    <a href="/"><font color="#3D9A13"> home </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/adminproyecto"><font color="#3D9A13"> Administrar Proyecto </font></a><img src="/static/img/flechaverde.png" width="12" height="10" />
    <a href="/usuario/crearproyecto"><font color="#3D9A13"> Nuevo proyecto </font></a>
</div>
<nav class="detalle">
    <h1>NUEVO PROYECTO</h1>
<form method='post' action=''>{% csrf_token %}

		<table class="max">
            <tr>
                        <th>Fecha de Inicio</th>
                        <td><input id="fechaInicio" type="date" name="fechaInicio"  required="True"></td>
            </tr>
            <tr>
                        <th>Fecha de Finalizacion</th>
                        <td><input id="fechaFin" type="date" name="fechaFin"  required="True"></td>
            </tr>

            {{formulario}}
        </table>

           <button class="button button-action" type="submit" name="Guardar" />Guardar</button>

           <a class="button button-caution" href="{% url 'usuario:adminproyecto' %}">Cancelar</a>

</form>
    </nav>
{% endblock %}
{% endif%}